function randomListItem() {
		var list = ["A robot learning to dance",
    "A tree growing out of a book",
    "A person skiing on a rainbow",
    "A dragonfly wearing sunglasses",
    "A shark playing a guitar",
    "A flower made of ice cream",
    "A giraffe driving a car",
    "A mermaid doing yoga on a rock",
    "A kangaroo riding a unicycle",
    "A snail carrying a backpack",
    "A superhero flying a kite",
    "A mouse using a typewriter",
    "A frog playing chess with a snail",
    "A monkey wearing a top hat and bowtie",
    "A fox riding a scooter",
    "A caterpillar wearing sneakers",
    "A unicorn eating pizza",
    "A penguin water skiing",
    "A raccoon painting a picture",
    "A turtle with a jetpack",
	"Pencil sharpener",
    "Compass",
    "Stapler",
    "Bottle opener",
    "Flashlight",
    "Corkscrew",
    "Watering can",
    "Bicycle pump",
    "Hairbrush",
    "Magnifying glass",
    "Tape measure",
    "Spatula",
    "Snow globe",
    "Paint roller",
    "Whistle",
    "Rolling pin",
    "Can opener",
    "Tea kettle",
    "Cookie cutter",
    "Feather duster"];
        var randomItem = list[Math.floor(Math.random() * (list.length-1))];
		var balls = document.getElementById("prompt");
        balls.textContent = "Prompt: " + randomItem ;
      }